<?php

// URLs públicas conservadas después de organizar los módulos.
return [
    'administracion/animales.php' => 'app/modulos/animales/administracion.php',
    'animales.php' => 'app/modulos/animales/catalogo.php',
    'animales/foto.php' => 'app/modulos/animales/foto.php',
    'acceso/disponibilidad_zoo.php' => 'app/modulos/acceso/disponibilidad_zoo.php',
    'acceso/guardar_disponibilidad.php' => 'app/modulos/acceso/guardar_disponibilidad.php',
    'acceso/historial_accesos.php' => 'app/modulos/acceso/historial_accesos.php',
    'acceso/procesar_accesos.php' => 'app/modulos/acceso/procesar_accesos.php',
    'admin.php' => 'app/modulos/administracion/panel.php',
    'administracion/habitats.php' => 'app/modulos/administracion/habitats.php',
    'administracion/permisos.php' => 'app/modulos/administracion/permisos.php',
    'administracion/usuarios.php' => 'app/modulos/administracion/usuarios.php',
    'cargar_imagenes.php' => 'app/modulos/tienda_admin/cargar_imagenes.php',
    'cliente.php' => 'app/modulos/clientes/panel.php',
    'comprar_boletos.php' => 'app/modulos/entradas/comprar.php',
    'cuidadores/asignar_animal.php' => 'app/modulos/cuidadores/asignar_animal.php',
    'cuidadores/asignar_tarea.php' => 'app/modulos/cuidadores/asignar_tarea.php',
    'cuidadores/cuidador_agregar.php' => 'app/modulos/cuidadores/cuidador_agregar.php',
    'cuidadores/cuidador_editar.php' => 'app/modulos/cuidadores/cuidador_editar.php',
    'cuidadores/cuidador_ver.php' => 'app/modulos/cuidadores/cuidador_ver.php',
    'cuidadores/cuidadores.php' => 'app/modulos/cuidadores/cuidadores.php',
    'cuidadores/editar_asignacion.php' => 'app/modulos/cuidadores/editar_asignacion.php',
    'cuidadores/horario_cuidador.php' => 'app/modulos/cuidadores/horario_cuidador.php',
    'cuidadores/tareas_cuidador.php' => 'app/modulos/cuidadores/tareas_cuidador.php',
    'detalle_ticket.php' => 'app/modulos/entradas/detalle.php',
    'eliminar_ticket.php' => 'app/modulos/entradas/eliminar.php',
    'empleado.php' => 'app/modulos/empleados/panel.php',
    'habitats.php' => 'app/modulos/habitats/catalogo.php',
    'index.php' => 'app/modulos/autenticacion/index.php',
    'inventario.php' => 'app/modulos/inventario/index.php',
    'login.php' => 'app/modulos/autenticacion/login.php',
    'logout.php' => 'app/modulos/autenticacion/logout.php',
    'mi_perfil.php' => 'app/modulos/usuario/perfil.php',
    'mis_entradas.php' => 'app/modulos/entradas/mis_entradas.php',
    'recuperar.php' => 'app/modulos/autenticacion/recuperar.php',
    'tienda_admin/producto_agregar.php' => 'app/modulos/tienda_admin/producto_agregar.php',
    'tienda_admin/producto_editar.php' => 'app/modulos/tienda_admin/producto_editar.php',
    'tienda_admin/producto_eliminar.php' => 'app/modulos/tienda_admin/producto_eliminar.php',
    'tienda_admin/productos.php' => 'app/modulos/tienda_admin/productos.php',
    'tienda/agregar_carrito.php' => 'app/modulos/tienda/agregar_carrito.php',
    'tienda/carrito.php' => 'app/modulos/tienda/carrito.php',
    'tienda/cliente.php' => 'app/modulos/tienda/cliente.php',
    'tienda/finalizar_compra.php' => 'app/modulos/tienda/finalizar_compra.php',
    'tienda/mis_compras.php' => 'app/modulos/tienda/mis_compras.php',
    'tienda/mis_tarjetas.php' => 'app/modulos/tienda/mis_tarjetas.php',
    'tienda/registrar_tarjeta.php' => 'app/modulos/tienda/registrar_tarjeta.php',
    'tienda/vaciar_carrito.php' => 'app/modulos/tienda/vaciar_carrito.php',
    'usuario/cambiar_contrasena.php' => 'app/modulos/usuario/cambiar_contrasena.php',
    'usuario/direccion.php' => 'app/modulos/usuario/direccion.php',
    'veterinario.php' => 'app/modulos/veterinario/panel.php',
];
